export enum AdSpaceStatus {
  AVAILABLE = "AVAILABLE",
  INACTIVE = "INACTIVE",
  RESERVED = "RESERVED",
  UNDER_MAINTENANCE = "UNDER_MAINTENANCE",
}

export enum AdSpaceType {
  BILLBOARD = "BILLBOARD",
  CITYBOARD = "CITYBOARD",
  DIGITAL_CITYLIGHT = "DIGITAL_CITYLIGHT",
  DIGITAL_KIOSK = "DIGITAL_KIOSK",
  INTERACTIVE_MONITOR = "INTERACTIVE_MONITOR",
  OUTDOOR_DCL = "OUTDOOR_DCL",
}

export enum AdSpaceVisibility {
  HIGH = "HIGH",
  LOW = "LOW",
  MEDIUM = "MEDIUM",
}
