export enum AdSpaceType {
  BILLBOARD = "BILLBOARD",
  CITYBOARD = "CITYBOARD",
  DIGITAL_CITYLIGHT = "DIGITAL_CITYLIGHT",
  INTERACTIVE_MONITOR = "INTERACTIVE_MONITOR",
  OUTDOOR_DCL = "OUTDOOR_DCL",
  DIGITAL_KIOSK = "DIGITAL_KIOSK",
}

export enum AdSpaceStatus {
  AVAILABLE = "AVAILABLE",
  RESERVED = "RESERVED",
  INACTIVE = "INACTIVE",
  UNDER_MAINTENANCE = "UNDER_MAINTENANCE",
}

export enum AdSpaceVisibility {
  HIGH = "HIGH",
  MEDIUM = "MEDIUM",
  LOW = "LOW",
}

export enum AdContentType {
  STATIC = "STATIC",
  DYNAMIC = "DYNAMIC",
  INTERACTIVE = "INTERACTIVE",
}
